---
# svc-shop
apiVersion: v1
kind: Service
metadata:
  name: svc-shop  # 인그레스 룰에 있는 svc-shop의 이름과 같아야 한다
spec:
  selector:
    app: shop
  ports:
  - port: 80
    targetPort: 80  # 타겟의 ip를 안 정해주면 기본적으로 클러스터 ip
---
# deploy-shop
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shop   
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: shop
        image: dhdtl12/portal:shop
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
